#!/usr/bin/env bash
set -euo pipefail

if [ $# -lt 5 ]; then
  echo "Usage: $0 <kas-file> <distro-codename> <feed-subfolder> <ref-name> <is-tagged-release> [output-file]" >&2
  exit 1
fi

KAS_FILE="$1"
DISTRO_CODENAME="$2"
FEED_SUBFOLDER="$3"
REF_NAME="$4"
IS_TAGGED_RELEASE="$5"
OUTPUT_FILE="${6:-kas-ci-override.yaml}"

if [ -z "$KAS_FILE" ] || [ -z "$DISTRO_CODENAME" ] || [ -z "$FEED_SUBFOLDER" ] || [ -z "$REF_NAME" ]; then
  echo "All arguments except the override file are required" >&2
  exit 1
fi

if ! command -v git >/dev/null 2>&1; then
  echo "git command not found" >&2
  exit 1
fi

SHORT_SHA=$(git rev-parse --short HEAD)
if [ -z "$SHORT_SHA" ]; then
  echo "Unable to determine git revision" >&2
  exit 1
fi

if [ "$IS_TAGGED_RELEASE" = "true" ]; then
  DISTRO_VERSION="$REF_NAME"
else
  case "$REF_NAME" in
    main)
      DISTRO_VERSION="1.0.0-continuous+$SHORT_SHA"
      ;;
    develop)
      DISTRO_VERSION="1.0.0-develop+$SHORT_SHA"
      ;;
    *)
      DISTRO_VERSION="1.0.0-branch+$SHORT_SHA"
      ;;
  esac
fi

cat > "$OUTPUT_FILE" <<EOF
header:
  version: 18
  includes:
    - $KAS_FILE

local_conf_header:
  ci_overrides: |
    # CI build overrides (generated by prepare-build-config.sh)
    DISTRO_CODENAME = "$DISTRO_CODENAME"
    CALCULINUX_FEED_SUBFOLDER = "$FEED_SUBFOLDER"
    DISTRO_VERSION = "$DISTRO_VERSION"
EOF

echo "distro_version=$DISTRO_VERSION"
echo "kas_override_file=$OUTPUT_FILE"
