#!/usr/bin/env bash
set -euo pipefail

if [ $# -lt 5 ]; then
  echo "Usage: $0 <kas-file> <distro-codename> <feed-subfolder> <ref-name> <is-tagged-release> [output-file]" >&2
  exit 1
fi

KAS_FILE="$1"
DISTRO_CODENAME="$2"
FEED_SUBFOLDER="$3"
REF_NAME="$4"
IS_TAGGED_RELEASE="$5"
OUTPUT_FILE="${6:-kas-ci-override.yaml}"

if [ -z "$KAS_FILE" ] || [ -z "$DISTRO_CODENAME" ] || [ -z "$FEED_SUBFOLDER" ] || [ -z "$REF_NAME" ]; then
  echo "All arguments except the override file are required" >&2
  exit 1
fi

if ! command -v git >/dev/null 2>&1; then
  echo "git command not found" >&2
  exit 1
fi

SHORT_SHA=$(git rev-parse --short HEAD)
if [ -z "$SHORT_SHA" ]; then
  echo "Unable to determine git revision" >&2
  exit 1
fi

# Strip characters that are unsafe in OE/DISTRO version labels
# (e.g. "/" and "~" from branch names)
sanitize_label() {
  printf '%s' "$1" | LC_ALL=C sed -e 's/[^A-Za-z0-9._+-]/-/g' | cut -c1-40
}

if [ "$IS_TAGGED_RELEASE" = "true" ]; then
  DISTRO_VERSION="$REF_NAME"
elif [ "$REF_NAME" = "main" ]; then
  DISTRO_VERSION="1.0.0-continuous+$SHORT_SHA"
elif [ "$REF_NAME" = "develop" ]; then
  DISTRO_VERSION="1.0.0-develop+$SHORT_SHA"
elif [[ "$REF_NAME" =~ ^([0-9]+)/merge$ ]]; then
  # GitHub pull_request events set ref_name to "<pr_number>/merge"
  DISTRO_VERSION="1.0.0-pr-${BASH_REMATCH[1]}+$SHORT_SHA"
else
  # Any other branch: embed a sanitized branch name
  LABEL=$(sanitize_label "$REF_NAME")
  [ -n "$LABEL" ] || LABEL="branch"
  DISTRO_VERSION="1.0.0-${LABEL}+$SHORT_SHA"
fi

cat > "$OUTPUT_FILE" <<EOF
header:
  version: 18
  includes:
    - $KAS_FILE

local_conf_header:
  ci_overrides: |
    # CI build overrides (generated by prepare-build-config.sh)
    CALCULINUX_CODENAME = "$DISTRO_CODENAME"
    CALCULINUX_FEED_SUBFOLDER = "$FEED_SUBFOLDER"
    CALCULINUX_VERSION = "$DISTRO_VERSION"
EOF

echo "distro_version=$DISTRO_VERSION"
echo "kas_override_file=$OUTPUT_FILE"
