#!/usr/bin/env python3
"""Generate lib/fonts/font_ter6x12.c from Terminus ter-u12n.bdf.

The kernel fbcon font is Terminus 6x12, the same base font as the cruft
userspace console default (console-font recipe), so boot messages and the
login terminal share one look. Glyphs are laid out in CP437 order like the
other built-in kernel fonts.

Usage: gen-font-ter6x12.py terminus-font-4.49.1/ter-u12n.bdf > font_ter6x12.c

The output is committed inside add-font-ter6x12.patch; rerun this only when
bumping Terminus.
"""
import sys

WIDTH, HEIGHT = 6, 12

# CP437 graphic glyphs for the control range (0x00 is blank) and 0x7F.
CP437_LOW = (
    "\u0000☺☻♥♦♣♠•◘○◙♂♀♪♫☼"
    "►◄↕‼¶§▬↨↑↓→←∟↔▲▼"
)


def cp437_to_unicode(i):
    if i < 0x20:
        return ord(CP437_LOW[i])
    if i == 0x7F:
        return 0x2302  # ⌂
    return ord(bytes([i]).decode("cp437"))


def parse_bdf(path):
    glyphs = {}
    fbb = None
    with open(path, encoding="latin-1") as f:
        lines = iter(f.read().splitlines())
    for line in lines:
        if line.startswith("FONTBOUNDINGBOX"):
            fbb = [int(v) for v in line.split()[1:]]
        elif line.startswith("ENCODING"):
            enc = int(line.split()[1])
        elif line.startswith("BBX"):
            bbx = [int(v) for v in line.split()[1:]]
        elif line == "BITMAP":
            rows = []
            for row in lines:
                if row == "ENDCHAR":
                    break
                rows.append(int(row, 16))
            glyphs[enc] = (bbx, rows)
    if fbb != [WIDTH, HEIGHT, 0, -2]:
        sys.exit(f"unexpected FONTBOUNDINGBOX {fbb}")
    return glyphs, fbb


def render(glyph, fbb):
    """Place a BDF glyph into a WIDTH x HEIGHT cell, one MSB-aligned byte per row."""
    (w, h, xoff, yoff), rows = glyph
    cell = [0] * HEIGHT
    nbytes = (w + 7) // 8
    top = (fbb[1] + fbb[3]) - (h + yoff)  # cell rows above the glyph box
    for r, bits in enumerate(rows):
        y = top + r
        if not 0 <= y < HEIGHT:
            continue
        # bits is left-aligned in nbytes*8 bits; shift to byte, apply xoff
        byte = (bits >> (nbytes * 8 - 8)) if nbytes > 1 else bits
        cell[y] = (byte >> (xoff - fbb[2])) & 0xFC
    return cell


def main():
    glyphs, fbb = parse_bdf(sys.argv[1])
    out = [
        "// SPDX-License-Identifier: OFL-1.1",
        "/*",
        " * Terminus 6x12 (ter-u12n) in CP437 order.",
        " * Copyright (C) 2020 Dimitar Toshkov Zhekov",
        " * Licensed under the SIL Open Font License, Version 1.1",
        " *",
        " * Generated by gen-font-ter6x12.py; do not edit.",
        " */",
        "#include <linux/font.h>",
        "",
        f"#define FONTDATAMAX {256 * HEIGHT}",
        "",
        "static const struct font_data fontdata_ter6x12 = {",
        "\t{ 0, 0, FONTDATAMAX, 0 }, {",
    ]
    missing = []
    for i in range(256):
        cp = cp437_to_unicode(i)
        glyph = glyphs.get(cp)
        if glyph is None:
            missing.append(f"0x{i:02X}/U+{cp:04X}")
            cell = [0] * HEIGHT
        else:
            cell = render(glyph, fbb)
        label = f" U+{cp:04X}" if cp else ""
        out.append(f"\t/* {i} 0x{i:02X}{label} */")
        for b in cell:
            pattern = format(b >> 2, "06b")
            out.append(f"\t0x{b:02X}, /* {pattern} */")
        if i != 255:
            out.append("")
    out += [
        "} };",
        "",
        "const struct font_desc font_ter_6x12 = {",
        "\t.idx\t= TER6x12_IDX,",
        '\t.name\t= "TER6x12",',
        f"\t.width\t= {WIDTH},",
        f"\t.height\t= {HEIGHT},",
        "\t.charcount = 256,",
        "\t.data\t= fontdata_ter6x12.data,",
        "\t.pref\t= 0,",
        "};",
    ]
    if missing:
        print("missing glyphs (left blank): " + ", ".join(missing), file=sys.stderr)
    print("\n".join(out))


if __name__ == "__main__":
    main()
