# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "calculinux-bsp-qemu"
BBFILE_PATTERN_calculinux-bsp-qemu = "^${LAYERDIR}/"
BBFILE_PRIORITY_calculinux-bsp-qemu = "99"

# OpenEmbedded compatibility information
# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_calculinux-bsp-qemu = "1"

LAYERDEPENDS_calculinux-bsp-qemu = "core calculinux-distro"
LAYERSERIES_COMPAT_calculinux-bsp-qemu = "scarthgap walnascar"
